// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcjwlvinduhofjzrcgqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjandsdmluZHVob2ZqenJjZ3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Njc5NTgsImV4cCI6MjA2OTA0Mzk1OH0.CpgA2vfFq0KOk8GjCBAkmY_H3Zrupd-pyv8lTDPQlhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});